apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seq
  labels:
    app: eshop
    service: seq
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: /
spec:
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /seq/*
        pathType: ImplementationSpecific
        backend:
          service: 
            name: seq
            port:
              number: 80