apiVersion: v1
kind: Service
metadata:
  name: webshoppingagg
  labels:
    app: eshop
    service: webshoppingagg
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 81
      protocol: TCP
      name: grpc
  selector:
    service: webshoppingagg
