kind: Deployment
apiVersion: apps/v1
metadata:
  name: basketdata
  labels:
    app: eshop
    service: basketdata
spec:
  replicas: 1
  selector:
    matchLabels:
      service: basketdata
  template:
    metadata:
      labels:
        app: eshop
        service: basketdata
    spec:
      containers:
        - name: basketdata
          image: redis:alpine
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
