apiVersion: v1
kind: Service
metadata:
  name: payment-api
  labels:
    app: eshop
    service: payment
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    service: payment
