apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-cm
  labels:
    app: eshop
    service: catalog
data:
  #APPINSIGHTS_INSTRUMENTATIONKEY: <key>
  ASPNETCORE_ENVIRONMENT: Development
  AzureServiceBusEnabled: "False"
  AzureStorageEnabled: "False"
  ConnectionString: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
  EventBusConnection: rabbitmq
  GRPC_PORT: "81"
  OrchestratorType: K8S
  PATH_BASE: /catalog-api
  PicBaseUrl: "{{ .Values.protocol }}://{{ .Values.host }}/apigateway/c/api/v1/catalog/items/[0]/pic/"
  PORT: "80"
  UseCustomizationData: "False"
