kind: Ingress
apiVersion: extensions/v1
metadata:
  name: basket
  labels:
    app: eshop
    service: basket
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /basket-api
          backend: 
            serviceName: basket-api
            servicePort: 80