apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webstatus
  labels:
    app: eshop
    service: webstatus
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /webstatus/*
        backend:
          serviceName: webstatus
          servicePort: 80