kind: ConfigMap
apiVersion: v1
metadata:
  name: webspa-cm
  labels:
    app: eshop
    service: webspa
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_URLS: http://0.0.0.0:80
  CallBackUrl: http://{{ .Values.aksLB }}
  DPConnectionString: basketdata
  BasketUrl: http://{{ .Values.aksLB }}/apigateway
  CallBackUrl: http://{{ .Values.aksLB }}/
  IdentityUrl: http://{{ .Values.aksLB }}/identity
  IdentityUrlHC: http://identity-api/hc
  IsClusterEnv: "True"
  OrchestratorType: K8S
  PATH_BASE: /
  PurchaseUrl: http://{{ .Values.aksLB }}/apigateway
  PurchaseUrlHC: http://ordering-api/hc
  SignalrHubUrl: http://{{ .Values.aksLB }}/apigateway
  UseCustomizationData: "True"
  UseLoadTest: "False"
