kind: ConfigMap
apiVersion: v1
metadata:
  name: coupon-cm
  labels:
    app: eshop
    service: coupon
data:
  ASPNETCORE_ENVIRONMENT: Development
  AzureServiceBusEnabled: "False"
  AzureStorageEnabled: "False"
  ConnectionString: mongodb://localhost:27017
  EventBusConnection: rabbitmq
  GRPC_PORT: "81"
  OrchestratorType: K8S
  PATH_BASE: /coupon-api
  PicBaseUrl: http://{{ .Values.aksLB }}/apigateway/c/api/v1/coupon/items/[0]/pic/
  PORT: "80"
  UseCustomizationData: "False"
