kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: coupon
  labels:
    app: eshop
    service: coupon
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /coupon-api
          pathType: Prefix
          backend:
            service:
              name: coupon-api
              port:
                number: 80
