kind: Service
apiVersion: v1
metadata:
  name: coupon-api
  labels:
    app: eshop
    service: coupon
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 81
      protocol: TCP
      name: grpc
  selector:
    service: coupon
