apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: identity
  labels:
    app: eshop
    service: identity
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /identity
        backend:
          serviceName: identity-api
          servicePort: 80