apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webspa
  labels:
    app: eshop
    service: webspa
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
{{- if eq .Values.protocol "https" }}
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: tls-secret
{{- end }}
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: webspa
            port: 
              number: 80