apiVersion: v1
kind: Service
metadata:
  name: webspa
  labels:
    app: eshop
    service: webspa
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service: webspa
