apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ordering
  labels:
    app: eshop
    service: ordering
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /ordering-api
        backend:
          serviceName: ordering-api
          servicePort: 80