kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: webstatus
  labels:
    app: eshop
    service: webstatus
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /webstatus
          pathType: Prefix
          backend:
            service:
              name: webstatus
              port:
                number: 80
