SET NOCOUNT ON
DECLARE @fktable TABLE(
    PKTABLE_QUALIFIER sysname, 
    PKTABLE_OWNER sysname, 
    PKTABLE_NAME sysname, 
    PKCOLUMN_NAME sysname, 
    FKTABLE_QUALIFIER sysname, 
    FKTABLE_OWNER sysname, 
    FKTABLE_NAME sysname, 
    FKCOLUMN_NAME sysname, 
    KEY_SEQ smallint, 
    UPDATE_RULE smallint, 
    DELETE_RULE smallint, 
    FK_NAME sysname, 
    PK_NAME sysname, 
    DEFERRABILITY smallint)

INSERT INTO @fktable (PKTABLE_QUALIFIER, PKTABLE_OWNER, PKTABLE_NAME, PKCOLUMN_NAME, FKTABLE_QUALIFIER, FKTABLE_OWNER, FKTABLE_NAME, FKCOLUMN_NAME, KEY_SEQ, UPDATE_RULE, DELETE_RULE, FK_NAME, PK_NAME, DEFERRABILITY)
EXEC sp_fkeys 'Orders'

INSERT INTO @fktable (PKTABLE_QUALIFIER, PKTABLE_OWNER, PKTABLE_NAME, PKCOLUMN_NAME, FKTABLE_QUALIFIER, FKTABLE_OWNER, FKTABLE_NAME, FKCOLUMN_NAME, KEY_SEQ, UPDATE_RULE, DELETE_RULE, FK_NAME, PK_NAME, DEFERRABILITY)
EXEC sp_fkeys 'Products'

INSERT INTO @fktable (PKTABLE_QUALIFIER, PKTABLE_OWNER, PKTABLE_NAME, PKCOLUMN_NAME, FKTABLE_QUALIFIER, FKTABLE_OWNER, FKTABLE_NAME, FKCOLUMN_NAME, KEY_SEQ, UPDATE_RULE, DELETE_RULE, FK_NAME, PK_NAME, DEFERRABILITY)
EXEC sp_fkeys 'Customers'

DECLARE @pktable TABLE(
    TABLE_QUALIFIER sysname, 
    TABLE_OWNER sysname, 
    TABLE_NAME sysname, 
    COLUMN_NAME sysname, 
    KEY_SEQ smallint, 
    PK_NAME sysname)

INSERT INTO @pktable (TABLE_QUALIFIER, TABLE_OWNER, TABLE_NAME, COLUMN_NAME, KEY_SEQ, PK_NAME)
EXEC sp_pkeys 'Orders'

INSERT INTO @pktable (TABLE_QUALIFIER, TABLE_OWNER, TABLE_NAME, COLUMN_NAME, KEY_SEQ, PK_NAME)
EXEC sp_pkeys 'Products'

INSERT INTO @pktable (TABLE_QUALIFIER, TABLE_OWNER, TABLE_NAME, COLUMN_NAME, KEY_SEQ, PK_NAME)
EXEC sp_pkeys 'ProductOrders'

INSERT INTO @pktable (TABLE_QUALIFIER, TABLE_OWNER, TABLE_NAME, COLUMN_NAME, KEY_SEQ, PK_NAME)
EXEC sp_pkeys 'Customers'

SELECT TABLE_NAME AS 'Table', COLUMN_NAME AS 'Column', PK_NAME AS 'Primary key'
FROM @pktable

PRINT ''

SELECT FKTABLE_NAME AS 'Table', FKCOLUMN_NAME AS 'Column', FK_NAME AS 'Foreign key'
FROM @fktable