apiVersion: v1
kind: Service
metadata:
  name: webstatus
  labels:
    app: eshop
    service: webstatus
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    service: webstatus
