apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: catalog
  labels:
    app: eshop
    service: catalog
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /catalog-api
        backend:
          serviceName: catalog-api
          servicePort: 80