apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: seq
  labels:
    app: eshop
    service: seq
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /seq(/|$)(.*)
        backend:
          serviceName: seq
          servicePort: 80