apiVersion: v1
kind: Service
metadata:
  name: basketdata
  labels:
    app: eshop
    service: basketdata
spec:
  ports:
    - port: 6379
      protocol: TCP
      name: redis
  selector:
    service: basketdata
