apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity
  labels:
    app: eshop
    service: identity
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
{{- if .Values.useHostName }}
  - host: {{ .Values.host }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /identity
        pathType: ImplementationSpecific
        backend:
          service:
            name: identity-api
            port: 
              number: 80