kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: identity
  labels:
    app: eshop
    service: identity
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /identity
          pathType: Prefix
          backend:
            service:
              name: identity-api
              port:
                number: 80
