apiVersion: v1
kind: Service
metadata:
  name: basket-api
  labels:
    app: eshop
    service: basket
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 81
      protocol: TCP
      name: grpc
  selector:
    service: basket
