kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: webspa
  labels:
    app: eshop
    service: webspa
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: webspa
              port:
                number: 80
